AllCops:
  # Include common Ruby source files.
  Include:
    - '**/*.gemspec'
    - '**/*.podspec'
    - '**/*.jbuilder'
    - '**/*.rake'
    - '**/*.opal'
    - '**/config.ru'
    - '**/Gemfile'
    - '**/Rakefile'
    - '**/Capfile'
    - '**/Guardfile'
    - '**/Podfile'
    - '**/Thorfile'
    - '**/Vagrantfile'
    - '**/Berksfile'
    - '**/Cheffile'
    - '**/Vagabondfile'
  Exclude:
    - 'vendor/gems/**/*'
    - 'db/schema.rb'
    - 'storage/**/*'
    - 'tmp/**/*'
Metrics/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false
